#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  3 10:38:08 2019

This script attempts a different form of detrending for TESS lightcurves, by 
cutting off the confusing peaks and troughs of stellar variability and then
fitting straight lines or splines

@author: phrhzn
"""

